### ISSUE TITLE
Placeholder replacement only works after the WHERE syntax

### ISSUE THREAD

**Issue by gvolpe** [AnormCypher/AnormCypher#34]
I want to create a generic query with a custom label (tag) and a custom relationship. This piece of code does not work. AnormCypher only parse the {userId} placeholder.

```scala
val socialTag = "social"
val relationship = "KNOWS"
val id = 123
val req: CypherStatement = Cypher( """ MATCH (a:{tag})-[:`{relationship}`]->(b) WHERE a.id={userId} RETURN a.id """)
          .on("tag" -> socialTag)
          .on("relationship" -> relationship)
          .on("userId" -> id)
```
Regards,
Gabriel.

**Comment by wfreeman** [comment]
This is a Neo limitation. You can't parameterize reltypes or labels. :(

**Comment by gvolpe** [comment]
Why not? I'm doing that in this way (as a workaround):

```scala
val query = "MATCH (a:" + socialTag + ")-[:" + relationship + "]->(b) WHERE a.id={userId} RETURN b.id"
val req: CypherStatement = Cypher(query).on("userId" -> id)
```

**Comment by wfreeman** [comment]
Yep, that's the only way you can do it.

**Comment by wfreeman** [comment]
It's mostly a query execution plan cache thing, from what I understand. You wouldn't be able to cache queries that have parameterized reltypes or labels. IMO they should offer to accept parameters (especially for create statements), with the caveat that the queries wouldn't be cached, or something.

**Comment by gvolpe** [comment]
Ok, thanks for the information provided.
