### ISSUE TITLE
Transaction events

### ISSUE THREAD

**Issue by alexanderweber** [AnormCypher/AnormCypher#37]
Regarding http://neo4j.com/docs/stable/transactions-events.html, do you plan on implementing any notification mechanism for neo4j transaction events?

**Comment by zarthross** [comment]
I don't believe those transaction events can be implemented.  AnormCypher uses the Rest-API and is thus limited by what can be done and transaction events are one of those items not supported by the Rest-API.  

Transactions in general however are likely on the roadmap. (see [Issue #15](https://github.com/AnormCypher/AnormCypher/issues/15) )

**Comment by Kai-Chen** [comment]
@zarthross is correct.  The Transaction Event Handler API is designed mainly for use by neo4j server plugins, which is out of the scope of AnormCypher.
