### ISSUE TITLE
Unable to access repo.anormcypher.org

### ISSUE THREAD

**Issue by devsathish** [AnormCypher/AnormCypher#47]
Hi,
Please reassign if this is not the right place. I'm trying to download anormcypher packages via SBT. Unfortunately, I'm not able to connect to repo.anormcypher.org (infact www.anormcypher.org is not accessible). Looks like the domain name got expired on 13th Nov 2015.
Any clues on how to get it back? Is there any alternative repo that I can use? Please let us know.

Exact URL that I'm trying: http://repo.anormcypher.org/org/anormcypher/anormcypher_2.11/0.6.0/anormcypher_2.11-0.6.0.pom

**Comment by Kai-Chen** [comment]
Eve's working on it.  In the meantime, you can run 'sbt publish-local' after cloning this repo to install a local copy.  If you want specifically the 0.6.0 version, the last commit is 57b0e4d4.

I will close this ticket when I can verify the server's back.

**Comment by freeeve** [comment]
I've renewed it, just needs to propagate. Sorry about that!

**Comment by freeeve** [comment]
At this point, it works for me.

**Comment by devsathish** [comment]
Thank you., I'm able to pull the packages from the server.
