### ISSUE TITLE
case CypherRow syntax is NOT YET SUPPORTED

### ISSUE THREAD

**Issue by torbjornvatn** [AnormCypher/AnormCypher#49]
Are there any plans for when the CypherRow pattern match will be implemented?

**Comment by Kai-Chen** [comment]
No plan yet.  The syntax is definitely nice; but transaction support is a functional feature and should have a higher priority.  I think there is incomplete work somewhere in the current code base (probably in tests), but I haven't had a block of time to sit down and figure out why it wasn't finished.

This feature is self-evident so anyone is welcome to give it a try without additional spec. :)
