### ISSUE TITLE
A number of the tests are failing with an exception

### ISSUE THREAD

**Issue by sheldon-white** [AnormCypher/AnormCypher#60]
After following the instructions in the README.md file:

BELL-MBP-SWHITE:/Users/swhite/projects/AnormCypher> sbt test
[info] Loading project definition from /Users/swhite/projects/AnormCypher/project
[info] Set current project to AnormCypher (in build file:/Users/swhite/projects/AnormCypher/)
[info] Compiling 1 Scala source to /Users/swhite/projects/AnormCypher/target/scala-2.11/test-classes...
[info] AnormCypherAsyncSpec:
[info] Cypher
[info] Exception encountered when attempting to run a suite with class name: org.anormcypher.async.AnormCypherAsyncSpec *** ABORTED ***
[info]   java.lang.RuntimeException: Expected '[' but got '"' / chr(34)
[info]   at scala.sys.package$.error(package.scala:27)
[info]   at play.api.libs.iteratee.Iteratee$$anonfun$run$1.apply(Iteratee.scala:396)
[info]   at play.api.libs.iteratee.Iteratee$$anonfun$run$1.apply(Iteratee.scala:389)
[info]   at play.api.libs.iteratee.StepIteratee$$anonfun$fold$2.apply(Iteratee.scala:706)
[info]   at play.api.libs.iteratee.StepIteratee$$anonfun$fold$2.apply(Iteratee.scala:706)
[info]   at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
[info]   at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
[info]   at play.api.libs.iteratee.Execution$trampoline$.executeScheduled(Execution.scala:120)
[info]   at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:71)
[info]   at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)

...

[info]   ...
[info] Run completed in 3 seconds, 465 milliseconds.
[info] Total number of tests run: 13
[info] Suites: completed 2, aborted 7
[info] Tests: succeeded 13, failed 0, canceled 0, ignored 0, pending 0
[info] *** 7 SUITES ABORTED ***
[error] Error during tests:
[error] 	org.anormcypher.async.Neo4jRESTAsyncSpec
[error] 	org.anormcypher.async.AnormCypherAsyncSpec
[error] 	org.anormcypher.CypherParserSpec
[error] 	org.anormcypher.AnormCypherSpec
[error] 	org.anormcypher.Neo4jTransactionSpec
[error] 	org.anormcypher.Neo4jRESTSpec
[error] 	org.anormcypher.async.CypherParserAsyncSpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 11 s, completed May 27, 2016 8:08:26 AM
BELL-MBP-SWHITE:/Users/swhite/projects/AnormCypher>

**Comment by Kai-Chen** [comment]
At some point in the 2.x series releases of Neo4j, the default configuration has changed to require login credential for all REST connections.  This is probably what you're seeing.  I don't think in the README there is an instruction to run `sbt test`.  The closest I can think of is running `sbt test:console`.  But if you do want to run `sbt test`, I would recommend adding the Neo4j credentials in `BaseAnormCypherSpec` so the tests can connect to your Neo4j server.

Sorry about the cryptic error message; it's one of the few drawbacks of a streaming transaction endpoint, which won't be able to use proper HTTP response status code to signal error (so even an error is transmitted using a 200 response).  Hopefully when we add support for Play 2.5 and have to rewrite json parsing we can add some better diagnostics message on error.

Btw, what's the molecule in your avatar? adenine or something like that? Very neat.

**Comment by foofighter2146** [comment]
@sheldon-white If you have installed Neo4j locally and use it only for testing and playing around with, disable auth in `neo4j.conf `before running the server for the first time by uncommenting the line

`dbms.security.auth_enabled=false`

You should not do this if you use a database with security issues. Then you should add credentials to `BaseAnormCypherSpec` like Kai-Chen wrote.

@Kai-Chen Maybe you could add these hints to README.md?

**Comment by Kai-Chen** [comment]
Documentation added.  Thanks!

**Comment by sheldon-white** [comment]
Thanks for the responses, I'll take a look.
(The molecule is called Indole. When very dilute it smells like Jasmine. In concentrated form it smells totally repulsive, like feces...)

**Comment by Kai-Chen** [comment]
See issue #61 also.
