### ISSUE TITLE
AnormCypher fails resolving dependencies

### ISSUE THREAD

**Issue by foofighter2146** [AnormCypher/AnormCypher#61]
If I try to install `AnormCypher` after cloning it from GitHub by calling sbt, the resolving of dependencies fails, because http://repo.lessis.me and http://repo.codahale.com are dead. The following changes in the `plugin.sbt` file work:

```
resolvers ++= Seq(
  "less is" at "http://repository.jetbrains.com",
//   "coda" at "http://repo.codahale.com",
  "Sonatype" at "http://oss.sonatype.org/content/repositories/releases/")

addSbtPlugin("me.lessis" % "ls-sbt" % "0.1.2")

//addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.5.1")
```
It seems that building AnormCypher works without "coda". Furthermore, current IDEA versions have a excellent sbt support coming with the Scala plugin, thus maybe 

`addSbtPlugin("com.github.mpeltonen" % "sbt-idea" % "1.5.1")`

could be removed too.

**Comment by Kai-Chen** [comment]
I don't think I use any of the plugins listed here.

@freeeve Are you okay with these plugins being removed?  I'm neutral either way.  Thanks!

**Comment by sheldon-white** [comment]
I've also run into this issue, thanks for taking a look.

**Comment by Kai-Chen** [comment]
@foofighter2146 Could you send the command you use that caused the dependency resolution failure?  I don't seem to have a way to test if my check-in worked or not.

Thanks!

**Comment by foofighter2146** [comment]
Running `sbt` in the project directory caused the failure after checking out a fresh copy of AnormCypher on a new installed machine.

But I updated now to version 0.9.2 of AnormCypher and could prove your changes by running `sbt test` (on Neo4j 3.0.3) successfully. 

Thank you for fixing this problem.

If it works for you too, we could close this issue.

**Comment by Kai-Chen** [comment]
Thanks!
