### ISSUE TITLE
neo4j-jdbc

### ISSUE THREAD

**Issue by gnomff** [AnormCypher/AnormCypher#65]
Not really an issue, more of a comment. I ran across this (newish) project https://github.com/neo4j-contrib/neo4j-jdbc - from some basic testing it looks like anorm/Hikari/neo4j-jdbc works just fine. 

`SQL"""create (tim:twoname {fname:"Tim", lname:"Foo"}), (katie:twoname {fname:"Katie", lname:"Bar"})""".execute`
`val names = SQL"""match (n:twoname) return n.fname, n.lname""".as(Macro.indexedParser[NameClass].*).map(_.fname)`

Is there anything I should be aware of that AnormCypher does that neo4j-jdbc will not be able to handle?

**Comment by Kai-Chen** [comment]
The driver's been in development for some time and should be faster than using the HTTP-based cypher endpoint.  When it's mature enough, i.e. after being used by a large number of users for some time, I think anormcypher can just become a thin wrapper of that in Scala, and maybe adding some DSL sugar not possible in Java.

I haven't followed up with its dev, so I don't know the current status.  But last time I looked, which was about 2 or 3 months ago, they don't have reactive streaming.  That's about all that anormcypher is worth right now :)

p.s. There *is* a mailing list for this kind of discussions, though not many ppl use it.  There's also a gitter chat room you can use for asking questions like this.

Cheers!

**Comment by gnomff** [comment]
Ok great, that answers all of my questions. Thanks!

**Comment by Kai-Chen** [comment]
One more thing that's different that I forgot to mention is that AnormCypher supports Neo4j 2.x, whereas the bolt protocol, and also neo4j-jdbc, only works with Neo4j 3.x.

Cheers!
