### ISSUE TITLE
repo.anormcypher.org down

### ISSUE THREAD

**Issue by fdv** [AnormCypher/AnormCypher#70]
Hello,

Your repository is down. http://repo.anormcypher.org/ neither answers nor ping, which makes impossible to install our project dependencies.

**Comment by Kai-Chen** [comment]
@freeeve I can ping the domain host, just not `repo.anormcypher.org`.

**Comment by freeeve** [comment]
It’s my fault. Will try to get it fixed ASAP. Sorry!

**Comment by freeeve** [comment]
I republished to the new repo. If I'm missing any versions, please let me know.
